faster=("Lad spillet begynde" "Åh gud!" "Nej, ikke det!" "Endelig!" "Det er det forkerte hul!" "Er det det hele?" "Fandens, strømerne!" "Nu!" "Jeg havde aldrig drømt om at det kunne være" "Hvis jeg gør det vil du ikke respektere mig!" "Nej, nej, gør det ved guldfisken!" "Sesam, luk dig op!" "EMR!" "Igen!" "Hurtigere!" "Hårdere!" "Hjælp!" "Tag mig hårdere!" "Er den inde endnu?" "Du er ikke min far!" "Hr. læge, er det nu propert?" "Hellige batmobil, Batman!" "Tag nu det flag, for pokker!" "Han er død, han er død!" "Tag mig, Robert!" "Jeg er liberal!" "Stik fire fingre ind!" "Sikke en elsker!" "Sig noget beskidt til mig, svin!" "Loftet trænger til maling," "Sug hårdere!" "Dyrene vil høre os!" "Ikke offentligt!" "Mit /dev/input har plads til det hele!" "Hvad hvis Spectrum hører os?" "Splitte mine bramsejl!" "Hov stop, jeg tror jeg flækker," "Skinke!" "Ohøj, hund!")
said=("brølte" "gøede" "kvækkede" "snerrede" "stønnede" "udklemte" "brummede" "grinte" "udspyede" "sukkede" "ejakulerede" "hostede" "stammede" "peb" "hvinede" "pev" "sagde" "argumenterede" "græd" "skreg" "råbte" "skinkede")
fadj=("sovsede" "eftersøgte" "uheldige" "lystige" "niårige" "tyrenakkede" "bisexuelle" "fantastiske" "søde" "nymfomanske" "bred-bækkenede" "fregnede" "45-årige" "hvidhårede" "fede" "hellige" "blinde" "skæggede" "blåøjede" "liderlige" "venlige" "klaverspillende" "øreslikkende" "menstruerende" "røvslikkende" "lesbiske" "behårede" "skinkende")
female=("sæk" "dagplejemor" "kvinde" "grevinde" "transvestit" "nymfoman" "jomfru" "læderfreak" "drag queen" "afpillede nonne" "bisexuelle dværg" "cheerleader" "kontorassistent" "sexuelle afviger" "regeringsagent" "småpige" "ceremonipingvin" "femme fatale" "chefdatter" "byggearbejder" "pølsemisbruger" "sekretær" "folketingsassistent" "bedstemor" "pingvin" "tyske hyrde" "stewardesse" "tjenerinde" "prostituerede" "slikmutter" "truckertøs" "mor til Spectrum" "trunte" "sæddunk" "feltmadras" "dronning" "prinsesse" "malkepige" "skønjomfru" "sygeplejeske" "matematiklærerinde" "frøken" "skolepige" "sjuft til Lindbo" "skinke")
asthe=("da den" "idet den" "mens den" "kort før den")
madjec=("aggressive" "savlende" "umættelige" "gale" "sataniske" "korpulente" "næsepillende" "hundebelurerende" "dryppende" "bredskuldrede" "oralfikserede" "veludrustede" "ufatteligt veludrustede" "godt udseende" "hjernedøde" "ufatteligt stive" "trebenede" "dampende" "kvindeudklædte" "stive" "sexgale" "vanvittige" "måtteslikkende" "vilde" "virile" "ekstreme" "cykelsædesniffende" "svenske" "sortsmuskede" "skinkende")
male=("redneck" "kamel" "spytslikker" "ærkegreve" "dværg" "medarbejder" "store dansker" "hingst" "slambert" "elektriske ål" "paranoide" "ulækre gamle mand" "homofile tigger" "friar" "advokat" "hårrodsfetishist" "pæne præst" "kyllingeelsker" "homoflamingo" "eks-cølibate" "stofsniffer" "kjolemand" "konstruktionsarbejder" "frisør" "tandlæge" "dommer" "socialmedarbejder" "viking" "hest" "tv-reparatør" "pizzaudbringer" "pave" "Fader" "læge" "gynækelog" "Batman" "skinke" "landsforræder" "svin")
diddled=("snød" "fortærrede" "græmsede" "mundede" "tungede" "tævede" "indstilte" "misbrugte" "forurenede" "gødede" "gennemborede" "omsorgsfuldt voldtog" "hammerede" "bad" "tungeslaskede" "sugede" "kneppede" "gned" "hævnskneppede" "onanerede med" "sluprede" "ferniserede" "kalibrerede" "pulede" "indstilte" "blitzkrieg'ede" "desavou'erede" "skinkede")
titadj=("alabaste" "lyserøde" "cremede" "rødmossede" "fugtige" "dunkende" "saftige" "hivende" "spændte" "elefantiske" "sukkulente" "skælvende" "rosa" "kugleformede" "opsvulmede" "dinglende" "blodige" "skævvredne" "dryppende" "osende" "faste" "hængende" "muskuløse" "kødfyldte" "faste" "spidse" "skinkede" "patformede")
knockers=("glober" "meloner" "højdedrag" "skud" "gajoler" "lunger" "forhøjninger" "skatte" "brød" "patter" "vestibule" "armhuler" "bryster" "jader" "albuer" "øjne" "lungehylstre" "kasser" "udposninger" "forlys" "fastpladelagre" "støddæmpere" "knæ" "spejlæg" "baller" "stødpuder" "øreflipper" "skinker" "intuitive brugerflade")
and=("og" "hvorefter han")
thrust=("kastede" "stødte" "klemte" "hamrede" "førte" "listede" "gled" "knaldede" "maste" "proppede" "dyppede" "avancerede" "vædrede" "indførte" "skubbede" "fyldte" "slæbte" "overførte" "rev" "tvang" "puffede" "indtog" "allokerede" "implementerede" "skinkede")
dongadj=("bristende" "lagte" "glitrende" "svulmende" "velsignede" "lilla" "sviende" "ophævede" "rigide" "hærgende" "vortede" "dampende" "rygende" "snabellignende" "frådende" "sprøjtende" "svinende" "forlorne" "årede" "forædte" "hestelignende" "pulserende" "enorme" "afgrunds-kløvende" "slangelignende" "kurvede" "stålindfattede" "glasbesatte" "knudrede" "kirurgisk modificerede" "metalforstærkede" "ømme" "hastigt skrumpende" "hævede" "minimale" "ranglede" "skinkende")
dong=("indtrænger" "gren" "stub" "lem" "kødpølse" "majestæt" "bovspryd" "gummiged" ,            "damphammer" "ladestok" "torsk" "joystick" "vejviser" "slambert" "motor" "motivation" "kødroulade" "stempel" "svupper" "redskab" "mandom" "slikkepind" "nyreprikker" "lysestage" "bandit" "arm" "testikel" "kugle" "finger" "fod" "tunge" "tissemand" "enøjede monster" "kødfløjte" "midterste ben" "diller" "gearstang" "penis" "holdkæftbolsje" "manuele styrepind" "anaconda" "python" "dolk" "kleine Führer" "skinke" "flagstang" "vatterpas" "ynglekæp" "messingstang" "budbringer" "Ethernet-kabel" "scepter" "sædpumpe" "parerstang" "lynafleder" "hobbyobjekt" "træningsapparat")
intoher=("ind i hendes" "efter hendes")
twatadj=("pulserende" "sultende" "glubrende" "bankende" "vidtåbne" "savlende" "indbydende" "mættede" "smaskende" "spindelvævsbesatte" "desperate" "slubrende" "glinsende" "dryppende" "arrede" "porøse" "milde" "lyserøde" "støvede" "stramme" "ildelugtende" "fugtige" "slappe" "stinkende" "tandløse" "velslidte" "hjulspors-afmærkede" "halvspiste" "sammentrukne" "velbesøgte" "taknemmelige" "rådnende" "tandbesatte" "skinkende" "fantastiske")
twat=("sump." "honningkrukke." "syltetøjsglas." "smørkasse." "pelsburger." "kirsebærstærte." "sprække." "revne." "hul." "cockpit." "hule." "fordybning." "helligste hellige." "skæggede østers." "kontinentalafgrund." "paradisiske dal." "røde flodbund." "lysthus." "babyfabrik." "palads." "røv." "rosenskud." "svælg." "øjenåbning." "svedkanal." "indre øre." "kropsåbning." "operationsar." "åbne sår." "navle." "mund." "næse." "fisse." "/dev/null." "portal til helvede." "mellemgulvsmund." "Cocio-dåse." "begivenhedshorizont." "fællesnævner." "skinke." "bagdør." "svingdør." "vandrehal." "hundredårskrigsstarter." "VGA-port." "nødudgang.")

selected_faster=${faster[$RANDOM % ${#faster[@]} ]}
selected_said=${said[$RANDOM % ${#said[@]} ]}
selected_fadj=${fadj[$RANDOM % ${#fadj[@]} ]}
selected_female=${female[$RANDOM % ${#female[@]} ]}
selected_asthe=${asthe[$RANDOM % ${#asthe[@]} ]}
selected_madjec=${madjec[$RANDOM % ${#madjec[@]} ]}
selected_male=${male[$RANDOM % ${#male[@]} ]}
selected_diddled=${diddled[$RANDOM % ${#diddled[@]} ]}
selected_titadj=${titadj[$RANDOM % ${#titadj[@]} ]}
selected_knockers=${knockers[$RANDOM % ${#knockers[@]} ]}
selected_and=${and[$RANDOM % ${#and[@]} ]}
selected_thrust=${thrust[$RANDOM % ${#thrust[@]} ]}
selected_dongadj=${dongadj[$RANDOM % ${#dongadj[@]} ]}
selected_dong=${dong[$RANDOM % ${#dong[@]} ]}
selected_intoher=${intoher[$RANDOM % ${#intoher[@]} ]}
selected_twatadj=${twatadj[$RANDOM % ${#twatadj[@]} ]}
selected_twat=${twat[$RANDOM % ${#twat[@]} ]}

echo "$selected_faster\" $selected_said den $selected_fadj $selected_female $selected_asthe $selected_madjec $selected_male $selected_diddled hendes $selected_titadj $selected_knockers $selected_and $selected_thrust sin $selected_dongadj $selected_dong $selected_intoher $selected_twatadj $selected_twat"
